server: 
   port: 7002
   
   #http://${eureka.instance.hostname}:${server.port}/eureka/
   #http://localhost:7001/eureka
eureka:
   instance:
      hostname: eureka7002.com
   client:
      #false means 
      register-with-eureka: false
      fetch-registry: false
      service-url:
         defaultZone: http://eureka7001.com:7001/eureka/