server:  
    port: 8001

spring: 
  application: 
    name: cloud-payment-service
  datasource: 
    url: jdbc:mysql://localhost:3306/spring_cache
    username: root
    password: root
    
eureka:
   client:
      register-with-eureka: true
      fetchRegistry: true
      service-url: 
         #defaultZone: http://localhost:7001/eureka
         defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka
   instance:
      instance-id: payment8001 #change hostname to be payment8002
      prefer-ip-address: true #show ip address by placing mouse over, showing 192.168.56.1:8001/actuator/info
      #check status using http://192.168.56.1:8002/actuator/health
    
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.carol.springcloud.entities
 

 